// <auto-generated />
using System;
using LibraryManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260723051110_FinalLibraryUpdate")]
    partial class FinalLibraryUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Paulo Coelho",
                            Genre = "Fiction",
                            IsAvailable = true,
                            PublicationYear = 1988,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 2,
                            Author = "James Clear",
                            Genre = "Self Help",
                            IsAvailable = true,
                            PublicationYear = 2018,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robert C. Martin",
                            Genre = "Programming",
                            IsAvailable = true,
                            PublicationYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Thomas H. Cormen",
                            Genre = "Computer Science",
                            IsAvailable = true,
                            PublicationYear = 2009,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Robert Kiyosaki",
                            Genre = "Finance",
                            IsAvailable = true,
                            PublicationYear = 1997,
                            Title = "Rich Dad Poor Dad"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowRecords");
                });

            modelBuilder.Entity("LibraryManagement.Models.LibrarianModel", b =>
                {
                    b.Property<int>("LibrarianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibrarianId");

                    b.ToTable("Librarians");

                    b.HasData(
                        new
                        {
                            LibrarianId = 1,
                            Age = 34,
                            Name = "Sarah Connor",
                            Phone = "555-0201"
                        },
                        new
                        {
                            LibrarianId = 2,
                            Age = 28,
                            Name = "John Doe",
                            Phone = "555-0202"
                        },
                        new
                        {
                            LibrarianId = 3,
                            Age = 45,
                            Name = "Michael Scott",
                            Phone = "555-0203"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.LoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoginModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "12345",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "myc546",
                            Username = "mycodingproject"
                        },
                        new
                        {
                            Id = 3,
                            Password = "myc",
                            Username = "my"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.StudentModel", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "alice@email.com",
                            Phone = "555-0101",
                            StudentName = "Alice Johnson"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "bob@email.com",
                            Phone = "555-0102",
                            StudentName = "Bob Smith"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "charlie@email.com",
                            Phone = "555-0103",
                            StudentName = "Charlie Brown"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.BorrowRecord", b =>
                {
                    b.HasOne("LibraryManagement.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
